format = """
â•­â”€$username@$hostname $directory$git_branch$git_commit$git_status$battery . $cmd_duration
â•°â”€ """

[directory]
truncation_length = 10
truncate_to_repo = false
format = "[$path](bold cyan)"

[git_branch]
symbol = ""
truncation_length = 30
truncation_symbol = ".."
ignore_branches = []
format = " [<$branch>](bold yellow)"
[git_commit]
tag_symbol = ""

[username]
format = "[$user](bold red)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[$hostname](bold red)"
trim_at = ".companyname.com"
disabled = false

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ï•¼"
unknown_symbol = "ï•¼"
empty_symbol = "ï–"
format = " [$symbol $percentage]($style)"
disabled = false
[[battery.display]]
threshold = 10
style = "bold red"
[[battery.display]]
threshold = 100
style = "bold green"

[cmd_duration]
min_time = 0

